spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    com.matador: DEBUG
    org.springframework.modulith: INFO
